"""PostGIS

Revision ID: 2c47b09fff3c
Revises: 
Create Date: 2026-09-05 20:17:39.038855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '2c47b09fff3c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis;")
    op.create_table('fpos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('region', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fpos_id'), 'fpos', ['id'], unique=False)
    op.create_table('logistics_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('capacity_kg', sa.Integer(), nullable=True),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logistics_providers_geom'), 'logistics_providers', ['geom'], unique=False)
    op.create_index(op.f('ix_logistics_providers_id'), 'logistics_providers', ['id'], unique=False)
    op.create_table('mandi_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('district', sa.String(length=200), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mandi_locations_geom'), 'mandi_locations', ['geom'], unique=False)
    op.create_index(op.f('ix_mandi_locations_id'), 'mandi_locations', ['id'], unique=False)
    op.create_table('price_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mandi', sa.String(length=200), nullable=False),
    sa.Column('commodity', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('p10_paise', sa.Integer(), nullable=False),
    sa.Column('p50_paise', sa.Integer(), nullable=False),
    sa.Column('p90_paise', sa.Integer(), nullable=False),
    sa.Column('forecast_confidence', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_forecasts_commodity'), 'price_forecasts', ['commodity'], unique=False)
    op.create_index(op.f('ix_price_forecasts_id'), 'price_forecasts', ['id'], unique=False)
    op.create_index(op.f('ix_price_forecasts_mandi'), 'price_forecasts', ['mandi'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_geom'), 'users', ['geom'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('buyer_demand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('crop', sa.String(length=100), nullable=False),
    sa.Column('desired_qty_kg', sa.Integer(), nullable=False),
    sa.Column('desired_grade', sa.String(length=5), nullable=True),
    sa.Column('max_price_paise_per_qtl', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_demand_buyer_id'), 'buyer_demand', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_buyer_demand_geom'), 'buyer_demand', ['geom'], unique=False)
    op.create_index(op.f('ix_buyer_demand_id'), 'buyer_demand', ['id'], unique=False)
    op.create_table('buyers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('verified_status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('farmers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fpo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fpo_id'], ['fpos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('fpo_id', sa.Integer(), nullable=True),
    sa.Column('crop', sa.String(length=100), nullable=False),
    sa.Column('quantity_kg', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('self_assay_answers', sa.JSON(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('price_min_paise_per_qtl', sa.Integer(), nullable=True),
    sa.Column('price_mid_paise_per_qtl', sa.Integer(), nullable=True),
    sa.Column('price_max_paise_per_qtl', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['fpo_id'], ['fpos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lots_crop'), 'lots', ['crop'], unique=False)
    op.create_index(op.f('ix_lots_farmer_id'), 'lots', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_lots_geom'), 'lots', ['geom'], unique=False)
    op.create_index(op.f('ix_lots_id'), 'lots', ['id'], unique=False)
    op.create_index(op.f('ix_lots_status'), 'lots', ['status'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('offered_price_paise_per_qtl', sa.Integer(), nullable=False),
    sa.Column('total_quantity_kg', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_buyer_id'), 'offers', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_offers_id'), 'offers', ['id'], unique=False)
    op.create_table('voice_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('audio_ref', sa.String(length=500), nullable=True),
    sa.Column('transcript', sa.String(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('intent_detected', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_interactions_id'), 'voice_interactions', ['id'], unique=False)
    op.create_table('batch_lot_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_lot_id', sa.Integer(), nullable=False),
    sa.Column('source_lot_id', sa.Integer(), nullable=False),
    sa.Column('quantity_contributed_kg', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['source_lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('farmer_user_id', sa.Integer(), nullable=False),
    sa.Column('buyer_user_id', sa.Integer(), nullable=False),
    sa.Column('provider_session_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farmer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_sessions_id'), 'call_sessions', ['id'], unique=False)
    op.create_table('offer_lots',
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('quantity_allocated_kg', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('offer_id', 'lot_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=True),
    sa.Column('payment_status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offer_id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('raised_by', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['raised_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disputes_id'), 'disputes', ['id'], unique=False)
    op.create_table('transaction_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_events_id'), 'transaction_events', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_events_transaction_id'), 'transaction_events', ['transaction_id'], unique=False)
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('spatial_ref_sys' ...
    op.drop_index(op.f('ix_transaction_events_transaction_id'), table_name='transaction_events')
    op.drop_index(op.f('ix_transaction_events_id'), table_name='transaction_events')
    op.drop_table('transaction_events')
    op.drop_index(op.f('ix_disputes_id'), table_name='disputes')
    op.drop_table('disputes')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('offer_lots')
    op.drop_index(op.f('ix_call_sessions_id'), table_name='call_sessions')
    op.drop_table('call_sessions')
    op.drop_table('batch_lot_members')
    op.drop_index(op.f('ix_voice_interactions_id'), table_name='voice_interactions')
    op.drop_table('voice_interactions')
    op.drop_index(op.f('ix_offers_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_buyer_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_lots_status'), table_name='lots')
    op.drop_index(op.f('ix_lots_id'), table_name='lots')
    op.drop_index(op.f('ix_lots_geom'), table_name='lots')
    op.drop_index(op.f('ix_lots_farmer_id'), table_name='lots')
    op.drop_index(op.f('ix_lots_crop'), table_name='lots')
    op.drop_index('idx_lots_geom', table_name='lots', postgresql_using='gist')
    op.drop_table('lots')
    op.drop_table('farmers')
    op.drop_table('buyers')
    op.drop_index(op.f('ix_buyer_demand_id'), table_name='buyer_demand')
    op.drop_index(op.f('ix_buyer_demand_geom'), table_name='buyer_demand')
    op.drop_index(op.f('ix_buyer_demand_buyer_id'), table_name='buyer_demand')
    op.drop_index('idx_buyer_demand_geom', table_name='buyer_demand', postgresql_using='gist')
    op.drop_table('buyer_demand')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_geom'), table_name='users')
    op.drop_index('idx_users_geom', table_name='users', postgresql_using='gist')
    op.drop_table('users')
    op.drop_index(op.f('ix_price_forecasts_mandi'), table_name='price_forecasts')
    op.drop_index(op.f('ix_price_forecasts_id'), table_name='price_forecasts')
    op.drop_index(op.f('ix_price_forecasts_commodity'), table_name='price_forecasts')
    op.drop_table('price_forecasts')
    op.drop_index(op.f('ix_mandi_locations_id'), table_name='mandi_locations')
    op.drop_index(op.f('ix_mandi_locations_geom'), table_name='mandi_locations')
    op.drop_index('idx_mandi_locations_geom', table_name='mandi_locations', postgresql_using='gist')
    op.drop_table('mandi_locations')
    op.drop_index(op.f('ix_logistics_providers_id'), table_name='logistics_providers')
    op.drop_index(op.f('ix_logistics_providers_geom'), table_name='logistics_providers')
    op.drop_index('idx_logistics_providers_geom', table_name='logistics_providers', postgresql_using='gist')
    op.drop_table('logistics_providers')
    op.drop_index(op.f('ix_fpos_id'), table_name='fpos')
    op.drop_table('fpos')
    # ### end Alembic commands ###
